// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eumkslwucfgpxwjwxaxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1bWtzbHd1Y2ZncHh3and4YXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MzEwODAsImV4cCI6MjA1MDUwNzA4MH0.3_tFHhGnFioMrpnKlsvcHm0JM1K-yFECZhsZYNYRwNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);